language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t brahmav/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true brahmav/react-test npm run test
   
after_success:
   - docker build -t brahmav/multi-client ./client
   - docker build -t brahmav/multi-nginx ./nginx
   - docker build -t brahmav/multi-server ./server
   - docker build -t brahmav/multi-worker ./worker
# Login to docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub

   - docker push brahmav/multi-client
   - docker push brahmav/multi-nginx
   - docker push brahmav/multi-server
   - docker push brahmav/multi-worker

deploy:
   edge: true
   provider: elasticbeanstalk
   region: us-east-1
   app: multi-Docker
   env: MultiDocker-env-1
   bucket_name: elasticbeanstalk-us-east-1-673616589655
   bucket_path: docker-multi
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
      secure: $AWS_SECRET_KEY
    